import {Injectable} from '@angular/core';

@Injectable()
export class ProfilesService {

  constructor() {}
  getProfiles() {
    return [
      {
        "first_name": "Gena",
        "last_name": "Runcieman",
        "email": "gruncieman0@last.fm",
        "project": "Fixflex",
        "image_url": "http://dummyimage.com/250x250.jpg/dddddd/000000",
        "active": false
      }, {
        "first_name": "Albie",
        "last_name": "Ley",
        "email": "aley1@aboutads.info",
        "project": "Zamit",
        "image_url": "http://dummyimage.com/250x250.png/ff4444/ffffff",
        "active": true
      }, {
        "first_name": "Gabriello",
        "last_name": "Gibling",
        "email": "ggibling2@mashable.com",
        "project": "Alpha",
        "image_url": "http://dummyimage.com/250x250.png/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Desdemona",
        "last_name": "Pickup",
        "email": "dpickup3@etsy.com",
        "project": "Subin",
        "image_url": "http://dummyimage.com/250x250.png/ff4444/ffffff",
        "active": true
      }, {
        "first_name": "Elnore",
        "last_name": "Othen",
        "email": "eothen4@squidoo.com",
        "project": "Voyatouch",
        "image_url": "http://dummyimage.com/250x250.bmp/ff4444/ffffff",
        "active": true
      }, {
        "first_name": "Magdalena",
        "last_name": "Hartin",
        "email": "mhartin5@usgs.gov",
        "project": "Ronstring",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Marj",
        "last_name": "Jeaves",
        "email": "mjeaves6@mapquest.com",
        "project": "Y-Solowarm",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": false
      }, {
        "first_name": "Geoffrey",
        "last_name": "Dechelette",
        "email": "gdechelette7@dailymail.co.uk",
        "project": "Quo Lux",
        "image_url": "http://dummyimage.com/250x250.jpg/cc0000/ffffff",
        "active": true
      }, {
        "first_name": "Marylinda",
        "last_name": "Hengoed",
        "email": "mhengoed8@gmpg.org",
        "project": "Bitwolf",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": true
      }, {
        "first_name": "Dean",
        "last_name": "Tappin",
        "email": "dtappin9@networkadvertising.org",
        "project": "Matsoft",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Laetitia",
        "last_name": "Santhouse",
        "email": "lsanthousea@artisteer.com",
        "project": "Lotstring",
        "image_url": "http://dummyimage.com/250x250.png/dddddd/000000",
        "active": true
      }, {
        "first_name": "Esdras",
        "last_name": "Alyokhin",
        "email": "ealyokhinb@spotify.com",
        "project": "Home Ing",
        "image_url": "http://dummyimage.com/250x250.jpg/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Jasmina",
        "last_name": "Witherop",
        "email": "jwitheropc@intel.com",
        "project": "Y-find",
        "image_url": "http://dummyimage.com/250x250.jpg/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Vickie",
        "last_name": "Titcom",
        "email": "vtitcomd@icio.us",
        "project": "Prodder",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": true
      }, {
        "first_name": "Glad",
        "last_name": "Mitchener",
        "email": "gmitchenere@washington.edu",
        "project": "Trippledex",
        "image_url": "http://dummyimage.com/250x250.bmp/cc0000/ffffff",
        "active": true
      }, {
        "first_name": "Cornie",
        "last_name": "Calverley",
        "email": "ccalverleyf@alibaba.com",
        "project": "Prodder",
        "image_url": "http://dummyimage.com/250x250.jpg/ff4444/ffffff",
        "active": false
      }, {
        "first_name": "Vick",
        "last_name": "Gomersall",
        "email": "vgomersallg@salon.com",
        "project": "Tres-Zap",
        "image_url": "http://dummyimage.com/250x250.png/5fa2dd/ffffff",
        "active": true
      }, {
        "first_name": "Beau",
        "last_name": "Nern",
        "email": "bnernh@epa.gov",
        "project": "Tresom",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Elane",
        "last_name": "Titterton",
        "email": "etittertoni@addtoany.com",
        "project": "Keylex",
        "image_url": "http://dummyimage.com/250x250.jpg/dddddd/000000",
        "active": true
      }, {
        "first_name": "Filmer",
        "last_name": "Rein",
        "email": "freinj@columbia.edu",
        "project": "Aerified",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Decca",
        "last_name": "Valder",
        "email": "dvalderk@census.gov",
        "project": "Trippledex",
        "image_url": "http://dummyimage.com/250x250.png/dddddd/000000",
        "active": true
      }, {
        "first_name": "Abbi",
        "last_name": "Volante",
        "email": "avolantel@lulu.com",
        "project": "Solarbreeze",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": false
      }, {
        "first_name": "Bamby",
        "last_name": "Vaggs",
        "email": "bvaggsm@ebay.co.uk",
        "project": "Alphazap",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": true
      }, {
        "first_name": "Deirdre",
        "last_name": "Dobbie",
        "email": "ddobbien@indiatimes.com",
        "project": "Wrapsafe",
        "image_url": "http://dummyimage.com/250x250.png/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Lotte",
        "last_name": "Stiegar",
        "email": "lstiegaro@dell.com",
        "project": "Cardify",
        "image_url": "http://dummyimage.com/250x250.bmp/cc0000/ffffff",
        "active": true
      }, {
        "first_name": "Konstantine",
        "last_name": "Bonifazio",
        "email": "kbonifaziop@google.com",
        "project": "Flowdesk",
        "image_url": "http://dummyimage.com/250x250.bmp/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Jorry",
        "last_name": "Joontjes",
        "email": "jjoontjesq@mayoclinic.com",
        "project": "Sub-Ex",
        "image_url": "http://dummyimage.com/250x250.jpg/dddddd/000000",
        "active": true
      }, {
        "first_name": "Beatrice",
        "last_name": "Tynewell",
        "email": "btynewellr@hhs.gov",
        "project": "Bamity",
        "image_url": "http://dummyimage.com/250x250.jpg/ff4444/ffffff",
        "active": false
      }, {
        "first_name": "Kathryne",
        "last_name": "Brotherhood",
        "email": "kbrotherhoods@livejournal.com",
        "project": "Cookley",
        "image_url": "http://dummyimage.com/250x250.png/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Ringo",
        "last_name": "Stotherfield",
        "email": "rstotherfieldt@vinaora.com",
        "project": "Zontrax",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": true
      }, {
        "first_name": "Tybie",
        "last_name": "Diable",
        "email": "tdiableu@altervista.org",
        "project": "Konklux",
        "image_url": "http://dummyimage.com/250x250.jpg/dddddd/000000",
        "active": false
      }, {
        "first_name": "Vanya",
        "last_name": "Skeene",
        "email": "vskeenev@oaic.gov.au",
        "project": "Namfix",
        "image_url": "http://dummyimage.com/250x250.bmp/dddddd/000000",
        "active": true
      }, {
        "first_name": "Urbain",
        "last_name": "Coveny",
        "email": "ucovenyw@phoca.cz",
        "project": "Stim",
        "image_url": "http://dummyimage.com/250x250.png/ff4444/ffffff",
        "active": true
      }, {
        "first_name": "Nickolai",
        "last_name": "Abell",
        "email": "nabellx@netvibes.com",
        "project": "Greenlam",
        "image_url": "http://dummyimage.com/250x250.jpg/dddddd/000000",
        "active": true
      }, {
        "first_name": "Jacquenette",
        "last_name": "Bezzant",
        "email": "jbezzanty@mayoclinic.com",
        "project": "Alphazap",
        "image_url": "http://dummyimage.com/250x250.bmp/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Daloris",
        "last_name": "Favela",
        "email": "dfavelaz@archive.org",
        "project": "Holdlamis",
        "image_url": "http://dummyimage.com/250x250.png/5fa2dd/ffffff",
        "active": true
      }, {
        "first_name": "Dayna",
        "last_name": "Bristoe",
        "email": "dbristoe10@apache.org",
        "project": "Duobam",
        "image_url": "http://dummyimage.com/250x250.bmp/cc0000/ffffff",
        "active": true
      }, {
        "first_name": "Ethan",
        "last_name": "Pomroy",
        "email": "epomroy11@alexa.com",
        "project": "Lotstring",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": true
      }, {
        "first_name": "Lenee",
        "last_name": "Ivanchov",
        "email": "livanchov12@ezinearticles.com",
        "project": "Tin",
        "image_url": "http://dummyimage.com/250x250.png/dddddd/000000",
        "active": false
      }, {
        "first_name": "Jethro",
        "last_name": "Tuson",
        "email": "jtuson13@adobe.com",
        "project": "Lotstring",
        "image_url": "http://dummyimage.com/250x250.jpg/ff4444/ffffff",
        "active": true
      }, {
        "first_name": "Alfonse",
        "last_name": "Worswick",
        "email": "aworswick14@domainmarket.com",
        "project": "Flexidy",
        "image_url": "http://dummyimage.com/250x250.png/dddddd/000000",
        "active": false
      }, {
        "first_name": "Kirby",
        "last_name": "Guslon",
        "email": "kguslon15@dropbox.com",
        "project": "Rank",
        "image_url": "http://dummyimage.com/250x250.jpg/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Mayne",
        "last_name": "Awcock",
        "email": "mawcock16@unesco.org",
        "project": "Veribet",
        "image_url": "http://dummyimage.com/250x250.bmp/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Viv",
        "last_name": "Mulderrig",
        "email": "vmulderrig17@sciencedaily.com",
        "project": "Flowdesk",
        "image_url": "http://dummyimage.com/250x250.jpg/ff4444/ffffff",
        "active": false
      }, {
        "first_name": "Vikky",
        "last_name": "Forman",
        "email": "vforman18@is.gd",
        "project": "Konklab",
        "image_url": "http://dummyimage.com/250x250.bmp/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Madella",
        "last_name": "Odger",
        "email": "modger19@pinterest.com",
        "project": "Gembucket",
        "image_url": "http://dummyimage.com/250x250.bmp/5fa2dd/ffffff",
        "active": true
      }, {
        "first_name": "Gretel",
        "last_name": "Teligin",
        "email": "gteligin1a@uol.com.br",
        "project": "Toughjoyfax",
        "image_url": "http://dummyimage.com/250x250.png/cc0000/ffffff",
        "active": false
      }, {
        "first_name": "Blayne",
        "last_name": "Bulled",
        "email": "bbulled1b@netvibes.com",
        "project": "Namfix",
        "image_url": "http://dummyimage.com/250x250.jpg/5fa2dd/ffffff",
        "active": false
      }, {
        "first_name": "Madeleine",
        "last_name": "Ibberson",
        "email": "mibberson1c@ameblo.jp",
        "project": "Y-Solowarm",
        "image_url": "http://dummyimage.com/250x250.png/dddddd/000000",
        "active": false
      }, {
        "first_name": "Marti",
        "last_name": "Featonby",
        "email": "mfeatonby1d@reddit.com",
        "project": "Bytecard",
        "image_url": "http://dummyimage.com/250x250.bmp/cc0000/ffffff",
        "active": true
      }
    ];
  }
}
